package KarmaTute.KarmaTute.aigateway;

public enum AITaskType {
    SKILL_EXTRACTION,
    DOCUMENT_UNDERSTANDING,
    SEMANTIC_MATCHING,
    MCQ_GENERATION,
    EXPLANATION,
    RUBRIC_ASSISTANCE,
    SCENARIO_EVALUATION,
    LANGUAGE_ASSISTANCE
}